# -*- coding: utf-8 -*-
"""AI_LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8XiAV2fOkfViZCF61qNbpoIRh-ok_o5
"""



"""# **List**

"""

#create a list of 10 integrals
a=[5,10,7,4,8,98,67,46,76,56]
print('list of 10 integrals is:',a)
#print('sum of the list is:',sum(a))
print('max of the list is:',max(a))
print('min of the list is:',min(a))

#add and remove element
a.append(30)
a.remove(10)
print('updated list:',a)

#sort ascending and descending
print('ascending of the list is:',sorted(a))
print('descending of the list is:',sorted(a,reverse=True))

"""# Tuples"""

#TUPLE OF 5 STRINGS
fruits=("mango","grapes","banana","pineapple","strawberry")
print('fruits are:',fruits)

#printing 2nd last element
print('2nd element is:', fruits[1])
print('last element is:', fruits[-1])

#try to modify tuple
#fruits.append("peach")
#fruits.remove("mango")
#print('updated tuple:',fruits)


#convert tuple into list and modify it
fruits_list=list(fruits)
fruits_list.append("peach")
fruits_list.remove("mango")
print('updated list:',fruits_list)

"""# Sets"""

#CREATE 2 SETS WITH SOME COMMON AND UNIQUE ELEMENTS
set1={1,2,3,4,5,6,7,8,9,10}
set2={5,6,7,8,9,10,11,12,13,14}
print('set1:',set1)
print('set2:',set2)

#perform union and intersection and differences of 2 sets
print('union of set1 and set2 is:',set1 | set2)
print('intersection of set1 and set2 is:',set1 & set2)
print('difference of set1 and set2 is:',set1.difference(set2))
print('difference of set2 and set1 is:',set2-set1)

"""# **Dictionary**"""

#create a key of students
students={'hashir': 99,'memoona':100,'ali':88,'Daneen':80,'Hadeed':59}

#print keys and values
print(students)
print(students.values())

#update values
students['Ali']=85
print(students)

"""# **Numpy**

# **Matplotlib**
"""