# -*- coding: utf-8 -*-
"""DatasetInfo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKF-sA8YPnLVkoKQiAPty9WBbP1VhvB7

**DatasetName**
"""

import numpy as np   #for numerical computation

import pandas as pd  #for data analysis

import matplotlib.pyplot as plt
  #for data visualization

File_path = '/content/drive/MyDrive/AI_LAB/Assignment 1/NF-ToN-IoT-V2.parquet'

df = pd.read_excel(path)

print(df.head())

"""NF-ToN-IoT

**Format**

semi structured
(CSV NetFlow data)
It is a benchmark dataset.

**Size**

174.3MB

**Total Instances**

~22.5 million
Train Instances      ~14.4 million
Test Instances       ~8.1 million

**5 Features**

Feature Name	Description
**1**
**Feature Name**       src_ip
**Description:**       *Source IP address* — the IP address of the device that initiated the connection.


**2.	**	.
**Feature Name**       dst_ip     
**Description:**       *Destination IP* address — the IP address of the device receiving the connection


**3.**
**Feature Name**       protocol   
**Description:**       The communication protocol used (e.g., TCP, UDP, ICMP).


**4.**
**Feature Name**       bytes  
**Description:**       Total number of bytes transferred in the network flow (both directions).


**5.**
**Feature Name**       packets  
**Description:**       Number of packets sent during the flow between the two endpoints.

**Labelled/Unlabelled**

The NF-ToN-IoT dataset is a labeled dataset.

**Type Of Dataset**

The NF-ToN-IoT dataset is primarily a numerical and categorical dataset.

**Machine Learning Models (Classical ML)**

1.Linear Regression
2.Logistic Regression
3	Decision Tree
4 Random Forest
5	Support Vector Machine (SVM)
6	K-Nearest Neighbors (KNN)
7 Naive Bayes
8	Gradient Boosting Machine (GBM)
9	XGBoost
10	AdaBoost
11	LightGBM
12	CatBoost
13	Hidden Markov Model (HMM)
14	Principal Component Analysis (PCA)

** Deep Learning Models**

15 Artificial Neural Network (ANN)
16	Convolutional Neural Network (CNN)
17	Recurrent Neural Network (RNN)
18	Long Short-Term Memory (LSTM)
19	Gated Recurrent Unit (GRU)
20	Autoencoder
21	Transformer
22	Generative Adversarial Network (GAN)

**Computer Vision Models**

23 AlexNet
24	VGGNet
25	ResNet
"""