# -*- coding: utf-8 -*-
"""KN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQjVFX1p0esg7iDFMOCbUJJjMBh0jdHd

**STEP 1**
"""

#Import libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

"""**STEP 2**"""

#STEP 1: LOAD DATASET
data = load_iris()         #load the iris dataset
x=data.data                #features(inputs)
y=data.target              #labels(output)

"""**STEP 3**"""

#spli data into trainig and testing sets(80% training , 20% testing)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

"""**STEP 4**"""

#create a KNN classifier with k=3
model=KNeighborsClassifier(n_neighbors=3)

"""**STEP 5**"""

#step 4: train the model
model.fit(X_train , y_train)

"""**STEP 6**"""

#step 5: predict on both training and test data
y_train_pred=model.predict(x_train)
y_test_pred=model.predict(x_test)

#step 6: calculate accuracy
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

"""**STEP 7**"""

#step 4: train the model
model.fit(x_train , y_train)

#step7 : print the results
print("Training Accuracy:",train_accuracy)
print("Testing Accuracy:",test_accuracy)