# -*- coding: utf-8 -*-
"""ResultReproduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdmZa-DXI9Df-HZTEVDtzsG6D3bYiCQH

# **Numpy**
"""

import numpy as np

# Create 1D array
arr = np.arange(10, 30) # Changed the range
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(30, 50) # Changed the range
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)

import numpy as np

# Create 1D array
arr = np.arange(1, 21)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(21, 41)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)