# -*- coding: utf-8 -*-
"""ResultReproduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdmZa-DXI9Df-HZTEVDtzsG6D3bYiCQH

# **Matplotlib**
"""

import matplotlib.pyplot as plt

# Line Plot
x = list(range(5, 15)) # Changed range
y = [i*3 for i in x] # Changed formula
plt.plot(x, y)
plt.title('Numbers vs Triple') # Changed title
plt.xlabel('Numbers')
plt.ylabel('Triple') # Changed label
plt.show()

# Bar Chart
students = ['Ali', 'Sara', 'Ahmed', 'Zara', 'Omar', 'Layla'] # Added a student
marks = [85, 90, 78, 92, 88, 95] # Added a mark
plt.bar(students, marks)
plt.title('Student Marks')
plt.xlabel('Students')
plt.ylabel('Marks')
plt.show()

# Pie Chart
categories = ['Category A', 'Category B', 'Category C', 'Category D'] # Added a category
values = [25, 40, 15, 20] # Changed values
plt.pie(values, labels=categories, autopct='%1.1f%%')
plt.title('Category Distribution')
plt.show()

"""# **Numpy**"""

import numpy as np

# Create 1D array
arr = np.arange(10, 30) # Changed the range
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(30, 50) # Changed the range
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)

import numpy as np

# Create 1D array
arr = np.arange(1, 21)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(21, 41)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)